config/routes.rb
Rails.application.routes.draw do
  resources :readies
  resources :initial_votes
  resources :users
  resources :votes
  resources :choices
  resources :matchups do
    get "/vote", to: "matchups#get_matchup_current_vote"
    post "/vote", to: "matchups#session_vote_on_matchup"
  end
  resources :rounds
  #get "rounds/index/:bracket_id", to: "rounds#filteredjson"
  resources :brackets do
    patch "/next", to: "brackets#activate_next_round"
    get "/waiting_users", to: "brackets#show_users"
    get "/waiting_ideas", to: "brackets#show_ideas"
    get "/start_game", to: "brackets#start_game"
    patch "/move_to_choices", to: "brackets#move_to_choices"
    get "/winner", to: "brackets#display_winner"
  end
  get "/bracket", to: "brackets#game_details"
  get "/current_choices", to: "brackets#choices_for_current_bracket"
  get "/user", to: "brackets#session_details"
  get "/bracket/round", to: "brackets#active_round_matchups"
  get "/rounds/for_bracket/:bracket_id", to: "rounds#rounds_for_bracket"
  get "/join", to: "brackets#join"
  get "/join_with_code", to: "brackets#join_with_code"
  get "/name", to: "users#new"
  get "/game", to: "brackets#game"
  get "/game/*other", to: "brackets#game"
  post "/ready_up", to: "brackets#ready_current_session"
  post "/unready_up", to: "brackets#unready_current_session"
  post "/unready_all", to: "brackets#unready_all"
  get "/current_initial_votes", to: "initial_votes#initial_votes_for_session"
  post "/initial_vote_for_session", to: "initial_votes#create_initial_vote_for_session"
  delete "/initial_votes", to: "initial_votes#destroy"
  delete "/leave", to: "brackets#leave"
  get "/broadcast", to: "brackets#test_cast"
  get "/ready_to_start", to: "brackets#ready_to_start"
  get "/help", to: "brackets#help"


  post "/bracket/matchup", to: "votes#create"
=begin
  Creation post requests for votes should have their data structured as follows
  {
    "vote": {
      "user_id": int
      "choice_id": int
      "matchup_id": int
    }
  }
=end
  root "brackets#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/bracket.rb
class Bracket < ApplicationRecord
	has_many :rounds, dependent: :destroy
	has_many :choices, dependent: :destroy
	has_and_belongs_to_many :users
	has_many :initial_votes, dependent: :destroy
	belongs_to :admin, class_name: "User", foreign_key: "admin_id", optional: true
	has_many :readies, foreign_key: :ready_bracket_id
	has_many :ready_users, class_name: "User", through: :readies, source: :ready_user, dependent: :destroy

	STATES = {
		uninitialized: -1,
		users: 0,
		choices: 1,
		voting: 2,
		matchup: 3,
		finish: 4
	}

	BROADCASTS = {
		ready: 0,
		state: 1,
		round: 2
	}
end

app/controllers/brackets_controller.rb
class BracketsController < ApplicationController
  before_action :set_bracket, only: %i[ show edit update destroy ]

  # GET /brackets or /brackets.json
  def index
    @brackets = Bracket.all
  end

  # GET /brackets/1 or /brackets/1.json
  def show
    @rounds = @bracket.rounds
  end

  # GET /brackets/new
  def new
    @bracket = Bracket.new
  end

  # GET /brackets/1/edit
  def edit
  end

  # POST /brackets or /brackets.json
  def create
    #@same_code_bracket = Bracket.find_by(code: params.dig(:bracket, :code))
    #@bracket = @same_code_bracket || Bracket.new(bracket_params)
    @bracket = Bracket.new
    @bracket.game_state = Bracket::STATES[:uninitialized] 
    @bracket.admin_id = nil
    code = (@bracket.hash % 1000000).to_s.rjust(6, padstr='0')
    while Bracket.find_by(code: code) do
      code = (code.hash % 1000000).to_s.rjust(6, padstr='0')
    end
    @bracket.code = code
    respond_to do |format|
      if @bracket.save
        session[:current_bracket_id] = @bracket.id
        format.html { redirect_to new_user_url, notice: "Bracket was successfully created." }
        format.json { render :show, status: :created, location: @bracket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bracket.errors, status: :unprocessable_entity }
      end
    end
  end

  def join
  end

  def join_with_code
    @bracket = Bracket.find_by(code: params[:code])
    respond_to do |format|
      if @bracket
        session[:current_bracket_id] = @bracket.id
        format.html { redirect_to new_user_url, notice: "Bracket was successfully joined." }
        format.json { render :show, status: :created, location: @bracket }
      else
        format.html { redirect_to join_url, notice: "No bracket with given code exists." }
      end
    end
  end


  # PATCH/PUT /brackets/1 or /brackets/1.json
  def update
    respond_to do |format|
      if @bracket.update(bracket_params)
        format.html { redirect_to bracket_url(@bracket), notice: "Bracket was successfully updated." }
        format.json { render :show, status: :ok, location: @bracket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bracket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brackets/1 or /brackets/1.json
  def destroy
    if !session_is_admin?(@bracket)
      return nil
    end

    @bracket.destroy
    respond_to do |format|
      format.html { redirect_to brackets_url, notice: "Bracket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def active_round
    set_bracket
    Round.find_by(bracket_id: @bracket.id, active: true)
  end
  helper_method :active_round

  def active_round_for_bracket(bracket_id)
    Round.find_by(bracket_id: bracket_id, active: true)
  end
  helper_method :active_round_for_bracket

  def next_round
    set_bracket
    Round.find_by(bracket_id: @bracket.id, round_num: active_round.round_num + 1)
  end

  helper_method :next_round

  def activate_next_round
    set_bracket
    unready_all(no_response: true)
    if @bracket.game_state == Bracket::STATES[:choices]
      start_game
      @bracket.game_state = Bracket::STATES[:voting] 
      @bracket.save
    elsif @bracket.game_state == Bracket::STATES[:voting]
      build_first_round
      @bracket.game_state = Bracket::STATES[:matchup]
      @bracket.save
      GameChannel.broadcast_to(@bracket, {type: Bracket::BROADCASTS[:state], game_state: Bracket::STATES[:matchup]})
      GameChannel.broadcast_to(@bracket, {type: Bracket::BROADCASTS[:round], round: active_round.round_num})
    elsif @bracket.game_state == Bracket::STATES[:matchup] and active_round.matchups.count > 1 #TODO, change to check for game_state == waiting_for_round when game_state is added
      build_next_round
      GameChannel.broadcast_to(@bracket, {type: Bracket::BROADCASTS[:round], round: active_round.round_num})
    elsif @bracket.game_state == Bracket::STATES[:matchup] and active_round.matchups.count == 1
      display_winner
      @bracket.game_state = Bracket::STATES[:finish] 
      GameChannel.broadcast_to(@bracket, {type: Bracket::BROADCASTS[:state], game_state: Bracket::STATES[:finish]})
      @bracket.save
    #TODO, change to check for game_state == end to display the end screen when end screen and game_state are added
    end
  end
  helper_method :activate_next_round


  def initial_votes_count(choice)
    initial_votes = InitialVote.where(choice_id: choice.id, bracket_id: choice.bracket_id)
    initial_votes.count
  end
  helper_method :initial_votes_count

  def bracket_size
    set_bracket
    choices = Choice.where(bracket_id: @bracket.id)
    num_choices = choices.count
    n = 1
    while n * 2 <= num_choices
      n *= 2
    end
    n
  end
  helper_method :bracket_size

  #Builds the next round, populating it with matchups with the choices which recieved the most initial votes
  #Should be called from the activate_next_round method, where set_bracket should have already been called
  def build_first_round
    round = Round.new(bracket_id: @bracket.id, round_num: 0, active: false)
    round.save
    choice_list = @bracket.choices.sort_by{|choice| initial_votes_count(choice)}
    choice_list.reverse!
    choice_list = choice_list.first(bracket_size)
    size = bracket_size
    n = 0
    while n < size / 2
      matchup = Matchup.new(round_id: round.id, first_choice_id: choice_list[n].id, second_choice_id: choice_list[size - (n + 1)].id)
      if !matchup.save
        respond_to do |format|
          format.html { redirect_to bracket_url(@bracket), notice: "Error trying to create matchups." }
          format.json { head 400 }
        end
        return nil
      end
      n += 1
    end 
    round.active = true
    round.save
    round
  end
  #helper_method :build_first_round

  def first_choice_votes_for_matchup(matchup)
    return Vote.where(matchup_id: matchup.id, choice_id: matchup.first_choice_id).count
  end
  def second_choice_votes_for_matchup(matchup)
    return Vote.where(matchup_id: matchup.id, choice_id: matchup.second_choice_id).count
  end
  #Should be called from the activate_next_round method, where set_bracket should have already been called
  def build_next_round
    #Active_round should be true
    previous_round = active_round
    if !previous_round
      #Respond with a fail if no active round was found
      respond_to do |format|
        format.html { redirect_to bracket_url(@bracket), notice: "Tried to build next round, but no active round was found." }
        format.json { head 400 }
      end
      return nil
    end
    next_round = Round.new(bracket_id: @bracket.id, round_num: previous_round.round_num + 1, active: false)
    next_round.save
    previous_matchups = previous_round.matchups
    n = 0
    while n < previous_matchups.count
      first_choice_id = first_choice_votes_for_matchup(previous_matchups[n]) > second_choice_votes_for_matchup(previous_matchups[n]) ? previous_matchups[n].first_choice_id : previous_matchups[n].second_choice_id
      second_choice_id = first_choice_votes_for_matchup(previous_matchups[n+1]) > second_choice_votes_for_matchup(previous_matchups[n+1]) ? previous_matchups[n+1].first_choice_id : previous_matchups[n+1].second_choice_id      
      matchup = Matchup.new(round_id: next_round.id, first_choice_id: first_choice_id, second_choice_id: second_choice_id)
      if !matchup.save
          respond_to do |format|
            format.html { redirect_to bracket_url(@bracket), notice: "Saving matchup for building new round failed." }
            format.json { head 400 }
          end
          #Kill the round so it doesn't have to be manually deleted
          next_round.destroy
        return nil
      end
      n += 2
    end
    next_round.active = true
    next_round.save
    previous_round.active = false
    previous_round.save
    next_round
  end
  def session_details
    status = :ok
    if not (logged_in? and in_game?)
      status = 401
    end
    respond_to do |format|
        format.html { redirect_to brackets_url, notice: "Tried to access a json file as html, add .json" }
        format.json { render :session_details, status: status}
     end
  end

  def active_round_details
  end

  def active_round_matchups
  end

  def home
  end

  def ready_to_start
    set_bracket
    if params[:current_game_state].to_i == @bracket.game_state
      ready_current_session(no_response: true)
    end
    respond_to do |format|
        format.html { redirect_to game_url, notice: "starting" }
        format.json { head :ok }
     end
  end

  def game
  end

  def test_cast
    set_bracket
    GameChannel.broadcast_to(@bracket, "Hello")
  end

  def show_users
    set_bracket

  end

  def show_ideas
    set_bracket
  end

  def start_game
    set_bracket
    #Advance game state from adding choices (1) to waiting/initial votes (2)
    GameChannel.broadcast_to(@bracket, {type: Bracket::BROADCASTS[:state], game_state: Bracket::STATES[:voting]})
    @bracket.game_state = Bracket::STATES[:voting] 
    @bracket.save
    @bracket.broadcast_replace_to("start_#{session[:current_bracket_id]}", target: "start_#{session[:current_bracket_id]}", partial:"brackets/start_game", locals: {bracket: Bracket.find_by(id: session[:current_bracket_id])})
  end
  #Advance game state from joining users (0) to adding choices (1)
  def move_to_choices
    set_bracket
    if !session_is_admin?(@bracket)
      return nil
    end
    GameChannel.broadcast_to(@bracket, {type: Bracket::BROADCASTS[:state], game_state: Bracket::STATES[:choices]})
    @bracket.game_state = Bracket::STATES[:choices] 
    @bracket.save
    @bracket.broadcast_replace_to("users_#{session[:current_bracket_id]}", target: "move_to_choices", partial:"brackets/move_to_choices", locals: {bracket: Bracket.find_by(id: session[:current_bracket_id])})
    respond_to do |format|

app/helpers/brackets_helper.rb
module BracketsHelper
end

app/views/brackets/_bracket.html.erb
<div id="<%= dom_id bracket %>">
  <p>
    <strong>Code:</strong>
    <%= bracket.code %>
  </p>
  <p>
    <strong>State:</strong>
    <%= bracket.game_state %>
  </p>
  <% if active_round_for_bracket(bracket.id)%>
  <p>
    <strong>Active Round:</strong>
    <%= active_round_for_bracket(bracket.id).round_num  %>
  </p>
  <% end %>

</div>

app/views/brackets/_form.html.erb
<%= form_with(model: bracket) do |form| %>

  <%= form.label "Create a new bracket" %>
  <%= form.button "Next &rarr;".html_safe, {type: "submit", class: "navigation"} %>

  <% if bracket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bracket.errors.count, "error") %> prohibited this bracket from being saved:</h2>

      <ul>
        <% bracket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/brackets/_join_form.html.erb
<%= form_with url: "/join_with_code", method: :get do |form| %>
  <%= form.label :code, "Enter your code" %>
  <%= form.text_field :code, {placeholder: "game code...", autocomplete: "off"} %>
  <% if notice %>
    <p><%= notice %></p>
  <% end %>

  <%= form.button "Next &rarr;".html_safe, {type: "submit", class: "navigation"} %>
<% end %>

app/views/brackets/_move_to_choices.html.erb
<turbo-frame id="move_to_choices">
	<%= link_to "Next", bracket_waiting_ideas_path(bracket), {data: {turbo_frame: "_top"}, class:"button small navigation next"}%>
</turbo_frame>

app/views/brackets/_start_game.html.erb
<turbo-frame id="start_<%=session[:current_bracket_id]%>">
	<%= link_to "Start Voting", bracket_path(bracket), {data: { turbo_frame: "_top" }, class:"button" }%>
</turbo_frame>

app/views/brackets/edit.html.erb
<h1>Editing bracket</h1>

<%= render "form", bracket: @bracket %>

<br>

<div>
  <%= link_to "Show this bracket", @bracket %> |
  <%= link_to "Back to brackets", brackets_path %>
</div>

app/views/brackets/game.html.erb
<%= provide :scripts do %>
    <%= vite_typescript_tag 'game.tsx' %>
<% end %>

<div id="root"></div>

app/views/brackets/help.html.erb
<%= provide :stylesheets do %>
    <%= stylesheet_link_tag "help", "data-turbo-track": "reload" %>
<% end %>

<main>
  <nav><%= link_to "Return", root_url, class: "button secondary small navigation" %></nav>
  <div class="logo-wrapper">
    <%= image_tag 'blobs/home-orange.svg', class: 'blob' %>
    <div style="flex-grow: 1;"></div>
    <h1 class="label">How to play!</h1>
    <h2>Joust your way to a decision!</h2>
  </div>
  <ul>
    <li>start by submitting what you want</li>
    <li>Vote on inputs to create a bracket</li>
    <li>Choose options in a head-to-head tournament and crown a champion!</li>
  </ul>
  <div class="button-group">
    <%= image_tag 'blobs/home-blue.svg', class: 'blob blue' %>
    <p>good luck, <strong>happy Jousting!</strong></p>
  </div>
</main>

app/views/brackets/home.html.erb
<%= provide :stylesheets do %>
    <%= stylesheet_link_tag "home", "data-turbo-track": "reload" %>
<% end %>

<main>
  <div class="logo-wrapper">
    <%= image_tag 'blobs/home-orange.svg', class: 'blob' %>
    <%= link_to "?", help_path, class: "button icon" %>
    <%= render "layouts/logo" %>
  </div>
  <div class="button-group">
    <%= image_tag 'blobs/home-blue.svg', class: 'blob blue' %>
    <%= button_to "Create", {controller: "brackets", action: "create"}, {method: :post, class: "button invert navigation"} %>
    <%= link_to "Join", join_path , class: "button flipped navigation" %>
  </div>
</main>

app/views/brackets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Brackets</h1>

<div id="brackets">
  <% @brackets.each do |bracket| %>
    <%= render bracket %>
    <p>
      <%= link_to "Show this bracket", bracket %>
    </p>
  <% end %>
</div>

<%= link_to "New bracket", new_bracket_path %>
<div>
  <p><%= link_to "See Brackets", brackets_path %></p>
  <p><%= link_to "See Rounds", rounds_path %></p>
  <p><%= link_to "See Matchups", matchups_path %></p>
  <p><%= link_to "See Choices", choices_path %></p>
  <p><%= link_to "See Votes", votes_path %></p>
</div>

app/views/brackets/new.html.erb
<%= provide :stylesheets do %>
    <%= stylesheet_link_tag "enter-code", "data-turbo-track": "reload" %>
<% end %>

<main>
  <div class="logo-wrapper">
    <%= image_tag 'blobs/enter-code-orange.svg', class: 'blob' %>
    <%= image_tag src="j-looking-down.svg", {class: "logo", alt: "J looking down", width: "175px", height: "255.72px"}%>
  </div>
  <%= render "form", bracket: @bracket %>
</main>

app/views/brackets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bracket %>

<% if @bracket.game_state == Bracket::STATES[:finish] %>
  <%= link_to "Display winner", bracket_winner_path(@bracket) %>
<% elsif session_is_admin?(@bracket.id) %>
  <%= button_to "Start next round", bracket_next_path(@bracket), {method: :patch, class: "button"} %>
<% end %>
<h2>Users </h2>
<% @bracket.users.each do |user| %>
  <%= render user %>
<% end %>
<h2>Choices </h2>
<strong>Bracket Size </strong><%= bracket_size %>
<% @bracket.choices.each do |choice| %>
  <turbo-frame id="<%= dom_id choice %>">
  <%= render choice %>
  <% if !active_round %>
    <strong>Initial Votes:</strong> <%= initial_votes_count(choice)%>
    <%= button_to "Vote for this choice", {controller: "initial_votes", action: "create", initial_vote: {bracket_id: @bracket.id, choice_id: choice.id, user_id: session[:current_user_id]}}, {method: :post, class: "button"} %>
    <% if session_is_admin?(@bracket.id) %>
      <%= button_to "Destroy", choice_path(choice), method: :delete %>
    <% end %>
  <% end %>
  </turbo-frame>
<% end %>
<% if session_is_admin?(@bracket.id) %>
<%= render "choices/form", {choice: Choice.new} %>
<% end %>
<% if active_round %>
  <%= link_to "View active round", round_path(active_round) %>
<% end %>


<% if session_is_admin?(@bracket.id) %>
<div>
  <%= link_to "Edit this bracket", edit_bracket_path(@bracket) %> |
  <% if active_round %>
  <%= link_to "View active round", round_path(active_round) %> |
  <% end %>
  <%= link_to "Back to brackets", brackets_path %>

  <%= button_to "Destroy this bracket", @bracket, method: :delete %>
</div>
<% end %>

app/views/brackets/show_ideas.html.erb
<%= provide :stylesheets do %>
    <%= stylesheet_link_tag "show-ideas", "data-turbo-track": "reload" %>
<% end %>

<main>
  <nav>
    <%= turbo_stream_from "choices_#{session[:current_bracket_id]}" %>
    <%= render partial: "leave_button" %>
  </nav>
  <div class="room-info">
    <p class="label">Done? Click Next!</p>
  </div>
  <turbo-frame id="choices_<%=session[:current_bracket_id]%>" class="choices">
    <% @bracket.choices.each do |choice| %>
      <%= render choice %>
    <% end %>
  </turbo-frame>
  <% if logged_in? and in_game? and @bracket.id == session[:current_bracket_id] %>
    <%= render "choices/form", {choice: Choice.new} %>
    <div class="row-wrapper">
      <div class="next-wrapper">
          <%= link_to "Next", "#{ready_to_start_url}?current_game_state=#{@bracket.game_state.to_s}", {class: "button small navigation", data: {turbo: false}} %>
          <%= image_tag src="blobs/show-ideas-green.svg", alt: "" %>
      </div>
    </div>
  <% end %>
</main>

app/views/brackets/show_users.html.erb
<%= provide :stylesheets do %>
    <%= stylesheet_link_tag "room", "data-turbo-track": "reload" %>
<% end %>

<main>
  <nav><%= render partial: "leave_button" %></nav>
  <div class="room-info">
    <p class="label">Room Code</p>
    <h1 class="room-code"><%= @bracket.code %></h1>
  </div>

  <%= turbo_stream_from "users_#{session[:current_bracket_id]}" %>
    <turbo-frame id="users_<%=session[:current_bracket_id]%>" class="users" target="_top">
      <div class="background"></div>
        
      <% @bracket.users.each do |user| %>
        <%= render user %>
      <% end %>
      
      <turbo-frame id="move_to_choices"  target="_top">
        <% if session_is_admin?(@bracket.id) and @bracket.game_state == Bracket::STATES[:users] %>
          <%= button_to "Next", bracket_move_to_choices_path(@bracket), {method: :patch, class:"button small navigation next"} %>
        <% elsif @bracket.game_state == Bracket::STATES[:choices] %>
          <%= link_to "Next", bracket_waiting_ideas_path(@bracket), {class:"button small navigation next"}%>
        <% end %>
      </turbo-frame>
    </turbo-frame>
    
</main>