config/routes.rb
Rails.application.routes.draw do
  resources :readies
  resources :initial_votes
  resources :users
  resources :votes
  resources :choices
  resources :matchups do
    get "/vote", to: "matchups#get_matchup_current_vote"
    post "/vote", to: "matchups#session_vote_on_matchup"
  end
  resources :rounds
  #get "rounds/index/:bracket_id", to: "rounds#filteredjson"
  resources :brackets do
    patch "/next", to: "brackets#activate_next_round"
    get "/waiting_users", to: "brackets#show_users"
    get "/waiting_ideas", to: "brackets#show_ideas"
    get "/start_game", to: "brackets#start_game"
    patch "/move_to_choices", to: "brackets#move_to_choices"
    get "/winner", to: "brackets#display_winner"
  end
  get "/bracket", to: "brackets#game_details"
  get "/current_choices", to: "brackets#choices_for_current_bracket"
  get "/user", to: "brackets#session_details"
  get "/bracket/round", to: "brackets#active_round_matchups"
  get "/rounds/for_bracket/:bracket_id", to: "rounds#rounds_for_bracket"
  get "/join", to: "brackets#join"
  get "/join_with_code", to: "brackets#join_with_code"
  get "/name", to: "users#new"
  get "/game", to: "brackets#game"
  get "/game/*other", to: "brackets#game"
  post "/ready_up", to: "brackets#ready_current_session"
  post "/unready_up", to: "brackets#unready_current_session"
  post "/unready_all", to: "brackets#unready_all"
  get "/current_initial_votes", to: "initial_votes#initial_votes_for_session"
  post "/initial_vote_for_session", to: "initial_votes#create_initial_vote_for_session"
  delete "/initial_votes", to: "initial_votes#destroy"
  delete "/leave", to: "brackets#leave"
  get "/broadcast", to: "brackets#test_cast"
  get "/ready_to_start", to: "brackets#ready_to_start"
  get "/help", to: "brackets#help"


  post "/bracket/matchup", to: "votes#create"
=begin
  Creation post requests for votes should have their data structured as follows
  {
    "vote": {
      "user_id": int
      "choice_id": int
      "matchup_id": int
    }
  }
=end
  root "brackets#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/choice.rb
class Choice < ApplicationRecord
	has_many :matchups, :class_name => "Matchup", :foreign_key => "first_choice_id"
	has_many :matchups, :class_name => "Matchup", :foreign_key => "second_choice_id"
	has_many :votes, dependent: :destroy
	has_many :initial_votes, dependent: :destroy
	belongs_to :user
	belongs_to :bracket
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :set_choice, only: %i[ show edit update destroy ]

  # GET /choices or /choices.json
  def index
    @choices = Choice.all
  end

  # GET /choices/1 or /choices/1.json
  def show
  end

  # GET /choices/new
  def new
    @choice = Choice.new
    if params.has_key?(:label)
      @choice.label = params[:label]
    end
    if session.has_key?(:current_user_id)
      @choice.user_id = :current_user_id
    end
    if session.has_key?(:current_bracket_id)
      @choice.bracket_id = :current_bracket_id
    end
  end

  # GET /choices/1/edit
  def edit
  end

  # POST /choices or /choices.json
  def create
    @choice = Choice.new(choice_params)

    if @choice.bracket.game_state != Bracket::STATES[:choices]
      return nil
    end

    respond_to do |format|
      if @choice.save
        format.turbo_stream {render turbo_stream: turbo_stream.append("choices", partial: "choices/choice", locals: {choice: @choice})}
        @choice.broadcast_append_to("choices_#{session[:current_bracket_id]}", target: "choices_#{session[:current_bracket_id]}")
        format.html { redirect_to bracket_waiting_ideas_url(session[:current_bracket_id]), notice: "Choice was successfully created." }
        format.json { render :show, status: :created, location: @choice }
      else
        format.html { redirect_to request.referrer, notice: "Invalid entry"}
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /choices/1 or /choices/1.json
  def update
    respond_to do |format|
      if @choice.update(choice_params)
        format.html { redirect_to choice_url(@choice), notice: "Choice was successfully updated." }
        format.json { render :show, status: :ok, location: @choice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1 or /choices/1.json
  def destroy
    if !session_is_admin?(Bracket.find_by(id: @choice.bracket_id))
      return nil
    end
    @choice.destroy
    respond_to do |format|
      format.turbo_stream {render turbo_stream: turbo_stream.remove(@choice) }
      @choice.broadcast_remove_to("choices_#{session[:current_bracket_id]}", target: @choice)
      format.html { redirect_to choices_url, notice: "Choice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choice
      @choice = Choice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def choice_params
      params.require(:choice).permit(:label, :user_id, :bracket_id, :reasoning)
    end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/views/choices/_choice.html.erb
<turbo-frame id="<%= dom_id choice %>" class="choice">
  <%# <% if defined?(session) && is_admin?(choice.bracket_id, choice.user_id) && Bracket.find_by(id: choice.bracket_id).game_state == 1 %>
    <%= button_to choice.label, choice_path(choice), {method: :delete, class: "text"} %>

  <%# <% else %>
    <%# <p class="option-text"><%= choice.label</p> %>
  <%# <% end %>
</turbo-frame>

app/views/choices/_form.html.erb
<%= form_with(model: choice, data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }) do |form| %>
  <div class="button-group">
    <%= form.text_field :label, {placeholder: "What do you want?", autocomplete: "off", required: true} %>
    <%# TODO: Use field for description of choice %>
    <%= form.text_field :reasoning, {placeholder: "Why?", autocomplete: "off"} %>
    <%= form.button "Submit", {type: "submit", class: "secondary"} %>
    <%= form.hidden_field :user_id, value: session[:current_user_id] || -1 %>
    <%= form.hidden_field :bracket_id, value: session[:current_bracket_id] || -1 %>
  </div>

  <% if choice.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

      <ul>
        <% choice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing choice</h1>

<%= render "form", choice: @choice %>

<br>

<div>
  <%= link_to "Show this choice", @choice %> |
  <%= link_to "Back to choices", choices_path %>
</div>

app/views/choices/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Choices</h1>

<div id="choices">
  <% @choices.each do |choice| %>
    <%= render choice %>
    <p>
      <%= link_to "Show this choice", choice %>
    </p>
  <% end %>
</div>

<%= link_to "New choice", new_choice_path %>
<div>
  <p><%= link_to "See Brackets", brackets_path %></p>
  <p><%= link_to "See Rounds", rounds_path %></p>
  <p><%= link_to "See Matchups", matchups_path %></p>
  <p><%= link_to "See Choices", choices_path %></p>
  <p><%= link_to "See Votes", votes_path %></p>
</div>

app/views/choices/new.html.erb
<h1>New choice</h1>

<%= render "form", choice: @choice %>

<br>

<div>
  <%= link_to "Back to choices", choices_path %>
</div>

app/views/choices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @choice %>

<div>
  <%= link_to "Edit this choice", edit_choice_path(@choice) %> |
  <%= link_to "Back to choices", choices_path %>

  <%= button_to "Destroy this choice", @choice, method: :delete %>
</div>