config/routes.rb
Rails.application.routes.draw do
  resources :readies
  resources :initial_votes
  resources :users
  resources :votes
  resources :choices
  resources :matchups do
    get "/vote", to: "matchups#get_matchup_current_vote"
    post "/vote", to: "matchups#session_vote_on_matchup"
  end
  resources :rounds
  #get "rounds/index/:bracket_id", to: "rounds#filteredjson"
  resources :brackets do
    patch "/next", to: "brackets#activate_next_round"
    get "/waiting_users", to: "brackets#show_users"
    get "/waiting_ideas", to: "brackets#show_ideas"
    get "/start_game", to: "brackets#start_game"
    patch "/move_to_choices", to: "brackets#move_to_choices"
    get "/winner", to: "brackets#display_winner"
  end
  get "/bracket", to: "brackets#game_details"
  get "/current_choices", to: "brackets#choices_for_current_bracket"
  get "/user", to: "brackets#session_details"
  get "/bracket/round", to: "brackets#active_round_matchups"
  get "/rounds/for_bracket/:bracket_id", to: "rounds#rounds_for_bracket"
  get "/join", to: "brackets#join"
  get "/join_with_code", to: "brackets#join_with_code"
  get "/name", to: "users#new"
  get "/game", to: "brackets#game"
  get "/game/*other", to: "brackets#game"
  post "/ready_up", to: "brackets#ready_current_session"
  post "/unready_up", to: "brackets#unready_current_session"
  post "/unready_all", to: "brackets#unready_all"
  get "/current_initial_votes", to: "initial_votes#initial_votes_for_session"
  post "/initial_vote_for_session", to: "initial_votes#create_initial_vote_for_session"
  delete "/initial_votes", to: "initial_votes#destroy"
  delete "/leave", to: "brackets#leave"
  get "/broadcast", to: "brackets#test_cast"
  get "/ready_to_start", to: "brackets#ready_to_start"
  get "/help", to: "brackets#help"


  post "/bracket/matchup", to: "votes#create"
=begin
  Creation post requests for votes should have their data structured as follows
  {
    "vote": {
      "user_id": int
      "choice_id": int
      "matchup_id": int
    }
  }
=end
  root "brackets#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :bracket
  has_many :matchups, dependent: :destroy
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: %i[ show edit update destroy ]

  # GET /rounds or /rounds.json
  def index
    @rounds = Round.all
  end

  # GET /rounds/1 or /rounds/1.json
  def show
  end

  # GET /rounds/new
  def new
    @round = Round.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds or /rounds.json
  def create
    @round = Round.new(round_params)

    respond_to do |format|
      if @round.save
        format.html { redirect_to round_url(@round), notice: "Round was successfully created." }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1 or /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to round_url(@round), notice: "Round was successfully updated." }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1 or /rounds/1.json
  def destroy
    @round.destroy

    respond_to do |format|
      format.html { redirect_to rounds_url, notice: "Round was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def rounds_for_bracket
    if params.has_key?(:bracket_id)
      respond_to do |format|
        format.html { redirect_to rounds_url, notice: "Tried to access a json API as html. Add .json to the end of your url." }
        format.json { render json: Round.where(bracket_id: params[:bracket_id]), status: :ok}
      end
    else
      respond_to do |format|
        format.html { head :no_content }
        format.json { head :no_content, status: :unprocessable_entity }
      end
    end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def round_params
      params.require(:round).permit(:bracket_id, :active, :round_num)
    end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_form.html.erb
<%= form_with(model: round) do |form| %>
  <% if round.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
        <% round.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :bracket_id, style: "display: block" %>
    <%= form.text_field :bracket_id %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.label :round_num, style: "display: block" %>
    <%= form.text_field :round_num %>
  </div>

  <div>
    <%= form.button "Next &rarr;".html_safe, {type: "submit", class: "navigation"} %>
  </div>
<% end %>

app/views/rounds/_round.html.erb
<div id="<%= dom_id round %>">
  <p>
    <strong>Belongs to Bracket:</strong>
    <%= round.bracket_id %>
  </p>
  <p>
    <strong>Active?</strong>
    <%= round.active %>
  </p>
  <p>
    <strong>Round Num:</strong>
    <%= round.round_num %>
  </p>


  <br />

  <% round.matchups.each do |matchup|%>
    <%= render matchup %>
    <br />
  <% end %>

</div>

app/views/rounds/edit.html.erb
<h1>Editing round</h1>

<%= render "form", round: @round %>

<br>

<div>
  <%= link_to "Show this round", @round %> |
  <%= link_to "Back to rounds", rounds_path %>
</div>

app/views/rounds/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rounds</h1>

<div id="rounds">
  <% @rounds.each do |round| %>
    <%= render round %>
    <%= link_to "Show this round", round %>
    <br></br>
  <% end %>
</div>

<%= link_to "New round", new_round_path %>
<div>
  <p><%= link_to "See Brackets", brackets_path %></p>
  <p><%= link_to "See Rounds", rounds_path %></p>
  <p><%= link_to "See Matchups", matchups_path %></p>
  <p><%= link_to "See Choices", choices_path %></p>
  <p><%= link_to "See Votes", votes_path %></p>
</div>

app/views/rounds/new.html.erb
<h1>New round</h1>

<%= render "form", round: @round %>

<br>

<div>
  <%= link_to "Back to rounds", rounds_path %>
</div>

app/views/rounds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @round %>

<div>
  <% if @round.matchups.count > 0 && @round.active %>
    <%= link_to "Start voting", matchup_path(@round.matchups.first.id) %>
  <% end %>
</div>

<div>
  <%= link_to "Edit this round", edit_round_path(@round) %> |
  <%= link_to "Back to rounds", rounds_path %> |
  <%= link_to "Back to bracket", bracket_path(@round.bracket_id)%>

  <%= button_to "Destroy this round", @round, method: :delete %>
</div>