config/routes.rb
Rails.application.routes.draw do
  resources :readies
  resources :initial_votes
  resources :users
  resources :votes
  resources :choices
  resources :matchups do
    get "/vote", to: "matchups#get_matchup_current_vote"
    post "/vote", to: "matchups#session_vote_on_matchup"
  end
  resources :rounds
  #get "rounds/index/:bracket_id", to: "rounds#filteredjson"
  resources :brackets do
    patch "/next", to: "brackets#activate_next_round"
    get "/waiting_users", to: "brackets#show_users"
    get "/waiting_ideas", to: "brackets#show_ideas"
    get "/start_game", to: "brackets#start_game"
    patch "/move_to_choices", to: "brackets#move_to_choices"
    get "/winner", to: "brackets#display_winner"
  end
  get "/bracket", to: "brackets#game_details"
  get "/current_choices", to: "brackets#choices_for_current_bracket"
  get "/user", to: "brackets#session_details"
  get "/bracket/round", to: "brackets#active_round_matchups"
  get "/rounds/for_bracket/:bracket_id", to: "rounds#rounds_for_bracket"
  get "/join", to: "brackets#join"
  get "/join_with_code", to: "brackets#join_with_code"
  get "/name", to: "users#new"
  get "/game", to: "brackets#game"
  get "/game/*other", to: "brackets#game"
  post "/ready_up", to: "brackets#ready_current_session"
  post "/unready_up", to: "brackets#unready_current_session"
  post "/unready_all", to: "brackets#unready_all"
  get "/current_initial_votes", to: "initial_votes#initial_votes_for_session"
  post "/initial_vote_for_session", to: "initial_votes#create_initial_vote_for_session"
  delete "/initial_votes", to: "initial_votes#destroy"
  delete "/leave", to: "brackets#leave"
  get "/broadcast", to: "brackets#test_cast"
  get "/ready_to_start", to: "brackets#ready_to_start"
  get "/help", to: "brackets#help"


  post "/bracket/matchup", to: "votes#create"
=begin
  Creation post requests for votes should have their data structured as follows
  {
    "vote": {
      "user_id": int
      "choice_id": int
      "matchup_id": int
    }
  }
=end
  root "brackets#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/matchup.rb
class Matchup < ApplicationRecord
  belongs_to :round
  belongs_to :first_choice, :class_name => "Choice", :foreign_key => "first_choice_id"
  belongs_to :second_choice, :class_name => "Choice", :foreign_key => "second_choice_id"
  has_many :votes, dependent: :destroy
end

app/controllers/matchups_controller.rb
class MatchupsController < ApplicationController
  before_action :set_matchup, only: %i[ show edit update destroy ]

  # GET /matchups or /matchups.json
  def index
    @matchups = Matchup.all
  end

  # GET /matchups/1 or /matchups/1.json
  def show
  end

  # GET /matchups/new
  def new
    @matchup = Matchup.new
  end

  # GET /matchups/1/edit
  def edit
  end

  # POST /matchups or /matchups.json
  def create
    @matchup = Matchup.new(matchup_params)

    respond_to do |format|
      if @matchup.save
        format.html { redirect_to matchup_url(@matchup), notice: "Matchup was successfully created." }
        format.json { render :show, status: :created, location: @matchup }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @matchup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matchups/1 or /matchups/1.json
  def update
    respond_to do |format|
      if @matchup.update(matchup_params)
        format.html { redirect_to matchup_url(@matchup), notice: "Matchup was successfully updated." }
        format.json { render :show, status: :ok, location: @matchup }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @matchup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matchups/1 or /matchups/1.json
  def destroy
    @matchup.destroy

    respond_to do |format|
      format.html { redirect_to matchups_url, notice: "Matchup was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def next_matchup
    set_matchup
    Matchup.where("id > ?", @matchup.id).where(round_id: @matchup.round_id).first
  end
  helper_method :next_matchup
  def next_round
    set_matchup
    Round.where("id > ?", @matchup.round_id).where(bracket_id: @matchup.round.bracket_id).first
  end
  helper_method :next_round
  def first_choice_votes
    set_matchup
    return Vote.where(matchup_id: @matchup.id, choice_id: @matchup.first_choice_id)
  end
  helper_method :first_choice_votes
  def second_choice_votes
    set_matchup
    return Vote.where(matchup_id: @matchup.id, choice_id: @matchup.second_choice_id)
  end
  helper_method :second_choice_votes

  def get_matchup_current_vote(no_response: false)
    set_matchup
    if !logged_in?
      return nil
    end
    @vote = Vote.find_by(matchup_id: @matchup.id, user_id: session[:current_user_id])
    if !no_response
      if @vote
        respond_to do |format|
          format.html { redirect_to vote_url(@vote), notice: "Vote found" }
          format.json { render "votes/show", status: :ok, location: @vote }
        end
      else
        respond_to do |format|
          format.html { head 404 }
          format.json { head 404 }
        end
      end
    end
    @vote
  end

  def session_vote_on_matchup
    set_matchup
    if !logged_in?
      return nil
    end
    if Vote.find_by(matchup_id: @matchup.id, user_id: session[:current_user_id])
      respond_to do |format|
        format.html { head 409 }
        format.json { head 409 }
      end
    else
      @vote = Vote.new
      @vote.user_id = session[:current_user_id]
      @vote.choice_id = params[:choice_id]
      @vote.matchup_id = params[:matchup_id]
      @vote.save
      respond_to do |format|
        format.html { redirect_to vote_url(@vote), notice: "Vote cast" }
        format.json { render "votes/show", status: :created, location: @vote }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_matchup
      if params[:id]
        @matchup = Matchup.find(params[:id])
      elsif params[:matchup_id]
        @matchup = Matchup.find(params[:matchup_id])
      end
    end

    # Only allow a list of trusted parameters through.
    def matchup_params
      params.require(:matchup).permit(:round_id, :first_choice_id, :second_choice_id)
    end
end

app/helpers/matchups_helper.rb
module MatchupsHelper
end

app/views/matchups/_form.html.erb
<%= form_with(model: matchup) do |form| %>
  <% if matchup.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(matchup.errors.count, "error") %> prohibited this matchup from being saved:</h2>

      <ul>
        <% matchup.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :round_id, style: "display: block" %>
    <%= form.text_field :round_id %>
  </div>
  <div>
    <%= form.label :first_choice_id, style: "display: block" %>
    <%= form.text_field :first_choice_id %>
  </div>
  <div>
    <%= form.label :second_choice_id, style: "display: block" %>
    <%= form.text_field :second_choice_id %>
  </div>

  <div>
    <%= form.button "Next &rarr;".html_safe, {type: "submit", class: "navigation"} %>
  </div>
<% end %>

app/views/matchups/_matchup.html.erb
<div id="<%= dom_id matchup %>">
  <p>
    <strong>Matchup <%= matchup.id %></strong>
  </p>
  <p>
    <strong>Round:</strong>
    <%= matchup.round_id %>
  </p>
  <div>
    <p>
      <%= render matchup.first_choice %> 
    </p>
  </div> 
  <div>
    <p>
      <%= render matchup.second_choice %> 
    </p>
  </div>
</div>

app/views/matchups/edit.html.erb
<h1>Editing matchup</h1>

<%= render "form", matchup: @matchup %>

<br>

<div>
  <%= link_to "Show this matchup", @matchup %> |
  <%= link_to "Back to matchups", matchups_path %>
</div>

app/views/matchups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Matchups</h1>

<div id="matchups">
  <% @matchups.each do |matchup| %>
    <%= render matchup %>
    <%= link_to "Show this matchup", matchup %>
    <br></br>
  <% end %>
</div>

<%= link_to "New matchup", new_matchup_path %>
<div>
  <p><%= link_to "See Brackets", brackets_path %></p>
  <p><%= link_to "See Rounds", rounds_path %></p>
  <p><%= link_to "See Matchups", matchups_path %></p>
  <p><%= link_to "See Choices", choices_path %></p>
  <p><%= link_to "See Votes", votes_path %></p>
</div>

app/views/matchups/new.html.erb
<h1>New matchup</h1>

<%= render "form", matchup: @matchup %>

<br>

<div>
  <%= link_to "Back to matchups", matchups_path %>
</div>

app/views/matchups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @matchup.first_choice %> 
<% if session[:current_user_id] != nil%>
  <% @current_user_id = session[:current_user_id] %>
<% else %>
  <% @current_user_id = 1 %>
<% end %>
<strong> Current votes: </strong> <%= first_choice_votes.count %>
<% if next_matchup != nil %>
  <%= button_to "Vote for this choice", {controller: "votes", action: "create", vote: {matchup_id: @matchup.id, choice_id: @matchup.first_choice_id, user_id: @current_user_id}, next_matchup: next_matchup}, {method: :post} %>
<% elsif next_round != nil %>
  <%= button_to "Vote for this choice", {controller: "votes", action: "create", vote: {matchup_id: @matchup.id, choice_id: @matchup.first_choice_id, user_id: @current_user_id}, next_round: next_round}, {method: :post} %>
<% else %>
  <%= button_to "Vote for this choice", {controller: "votes", action: "create", vote: {matchup_id: @matchup.id, choice_id: @matchup.first_choice_id, user_id: @current_user_id}}, {method: :post} %>
<% end %>

<%= render @matchup.second_choice %>
<strong> Current votes: </strong> <%= second_choice_votes.count %>
<% if next_matchup != nil %>
  <%= button_to "Vote for this choice", {controller: "votes", action: "create", vote: {matchup_id: @matchup.id, choice_id: @matchup.second_choice_id, user_id: @current_user_id}, next_matchup: next_matchup}, {method: :post} %>
<% elsif next_round != nil %>
  <%= button_to "Vote for this choice", {controller: "votes", action: "create", vote: {matchup_id: @matchup.id, choice_id: @matchup.second_choice_id, user_id: @current_user_id}, next_round: next_round}, {method: :post} %>
<% else %>
  <%= button_to "Vote for this choice", {controller: "votes", action: "create", vote: {matchup_id: @matchup.id, choice_id: @matchup.second_choice_id, user_id: @current_user_id}}, {method: :post} %>
<% end %>

<div>
  <% if next_matchup != nil %>
    <%= link_to "Next matchup", matchup_path(next_matchup) %>
  <% else %>
    <% if next_round != nil %>
      <%= link_to "Next round", round_path(next_round) %>
    <% end %>
  <% end %>
</div>

<div>
  <%= link_to "Edit this matchup", edit_matchup_path(@matchup) %> |
  <%= link_to "Back to matchups", matchups_path %> |
  <%= link_to "Back to round", round_path(@matchup.round_id) %>

  <%= button_to "Destroy this matchup", @matchup, method: :delete %>
</div>